spring:
  application:
    name: mobileshop-api-seller-feign

server:
  port: 9005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true