server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: mobileshop-api-seller-feign
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8777
  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true